version: "3.10"

services:
  middleware_service:
    build: middleware_service
    restart: always
    ports:
      - "1000:1000"
    networks:
      - lognet

  account_db:
    image: postgres:13.4
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresqlaccount_db/data/
    env_file:
      - .envs/.account_db_env
    networks:
      - lognet

  account_service:
    build: account_service
    restart: always
    ports:
      - "2000:2000"
    depends_on:
      - account_db
    env_file:
      - .envs/.auth_secret_env
    networks:
      - lognet

  organization_db:
    image: postgres:13.4
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresqlorganization_db/data/
    env_file:
      - .envs/.organization_db_env
    networks:
      - lognet

  organization_service:
    build: organization_service
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - organization_db
    env_file:
      - .envs/.auth_secret_env
    networks:
      - lognet

volumes:
  postgres_data:
  redis_data:
  static_value:
  media_value:

networks:
  lognet:
    driver: bridge
