import os


PROTOCOL = "http"
MIDDLEWARE_HOST = os.environ.get("MIDDLEWARE_HOST", "middleware_service")
MIDDLEWARE_PORT = os.environ.get("MIDDLEWARE_PORT", 1000)
MIDDLEWARE_URL = f"{PROTOCOL}://{MIDDLEWARE_HOST}:{MIDDLEWARE_PORT}"
MIDDLEWARE_V1_API_PREFIX = os.environ.get("MIDDLEWARE_API_PREFIX", "api/v1")


URL_CHECK_ACCOUNT = "middleware/check_account"

MIDDLEWARE_URL_CHECK_ACCOUNT = (
    f"{MIDDLEWARE_URL}/{MIDDLEWARE_V1_API_PREFIX}/{URL_CHECK_ACCOUNT}"
)
