import os


PROTOCOL = "http"
MIDDLEWARE_HOST = os.environ.get("MIDDLEWARE_HOST", "middleware_service")
MIDDLEWARE_PORT = os.environ.get("MIDDLEWARE_PORT", 1000)
MIDDLEWARE_URL = f"{PROTOCOL}://{MIDDLEWARE_HOST}:{MIDDLEWARE_PORT}"
MIDDLEWARE_V1_API_PREFIX = os.environ.get("MIDDLEWARE_API_PREFIX", "api/v1")


URL_CREATE_OR_UPDATE_ACCOUNT = "middleware/account/create_or_update"

MIDDLEWARE_URL_CREATE_OR_UPDATE_ACCOUNT = (
    f"{MIDDLEWARE_URL}/{MIDDLEWARE_V1_API_PREFIX}/{URL_CREATE_OR_UPDATE_ACCOUNT}"
)
