import os


PROTOCOL = "http"

# ORGANIZATION_SERVICE
ORGANIZATION_HOST = os.environ.get("ORGANIZATION_HOST", "organization_service")
ORGANIZATION_PORT = os.environ.get("ORGANIZATION_PORT", 3000)
ORGANIZATION_URL = f"{PROTOCOL}://{ORGANIZATION_HOST}:{ORGANIZATION_PORT}"
ORGANIZATION_V1_API_PREFIX = os.environ.get("MIDDLEWARE_API_PREFIX", "api/v1")

URL_CREATE_OR_UPDATE_ACCOUNT = "middleware/account/create_or_update"

ORGANIZATION_URL_CREATE_OR_UPDATE_ACCOUNT = (
    f"{ORGANIZATION_URL}/{ORGANIZATION_V1_API_PREFIX}/{URL_CREATE_OR_UPDATE_ACCOUNT}"
)


ACCOUNT_HOST = os.environ.get("ACCOUNT_HOST", "account_service")
ACCOUNT_PORT = os.environ.get("ACCOUNT_PORT", 2000)
ACCOUNT_V1_API_PREFIX = os.environ.get("MIDDLEWARE_API_PREFIX", "api/v1")
ACCOUNT_URL = f"{PROTOCOL}://{ACCOUNT_HOST}:{ACCOUNT_PORT}"

URL_CHECK_ACCOUNT = "middleware/check_account"

ACCOUNT_URL_CHECK_ACCOUNT = (
    f"{ACCOUNT_URL}/{ORGANIZATION_V1_API_PREFIX}/{URL_CHECK_ACCOUNT}"
)